/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as SummaryRouteImport } from './routes/summary'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as QualityRouteImport } from './routes/quality'
import { Route as MultilingualRouteImport } from './routes/multilingual'
import { Route as LineageRouteImport } from './routes/lineage'
import { Route as GovernanceRouteImport } from './routes/governance'
import { Route as ExportRouteImport } from './routes/export'
import { Route as ExecutiveRouteImport } from './routes/executive'
import { Route as DictionaryRouteImport } from './routes/dictionary'
import { Route as DatasetOverviewRouteImport } from './routes/dataset-overview'
import { Route as DataSourcesRouteImport } from './routes/data-sources'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as AskRouteImport } from './routes/ask'
import { Route as IndexRouteImport } from './routes/index'

const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const SummaryRoute = SummaryRouteImport.update({
  id: '/summary',
  path: '/summary',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const QualityRoute = QualityRouteImport.update({
  id: '/quality',
  path: '/quality',
  getParentRoute: () => rootRouteImport,
} as any)
const MultilingualRoute = MultilingualRouteImport.update({
  id: '/multilingual',
  path: '/multilingual',
  getParentRoute: () => rootRouteImport,
} as any)
const LineageRoute = LineageRouteImport.update({
  id: '/lineage',
  path: '/lineage',
  getParentRoute: () => rootRouteImport,
} as any)
const GovernanceRoute = GovernanceRouteImport.update({
  id: '/governance',
  path: '/governance',
  getParentRoute: () => rootRouteImport,
} as any)
const ExportRoute = ExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => rootRouteImport,
} as any)
const ExecutiveRoute = ExecutiveRouteImport.update({
  id: '/executive',
  path: '/executive',
  getParentRoute: () => rootRouteImport,
} as any)
const DictionaryRoute = DictionaryRouteImport.update({
  id: '/dictionary',
  path: '/dictionary',
  getParentRoute: () => rootRouteImport,
} as any)
const DatasetOverviewRoute = DatasetOverviewRouteImport.update({
  id: '/dataset-overview',
  path: '/dataset-overview',
  getParentRoute: () => rootRouteImport,
} as any)
const DataSourcesRoute = DataSourcesRouteImport.update({
  id: '/data-sources',
  path: '/data-sources',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AskRoute = AskRouteImport.update({
  id: '/ask',
  path: '/ask',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ask': typeof AskRoute
  '/chat': typeof ChatRoute
  '/data-sources': typeof DataSourcesRoute
  '/dataset-overview': typeof DatasetOverviewRoute
  '/dictionary': typeof DictionaryRoute
  '/executive': typeof ExecutiveRoute
  '/export': typeof ExportRoute
  '/governance': typeof GovernanceRoute
  '/lineage': typeof LineageRoute
  '/multilingual': typeof MultilingualRoute
  '/quality': typeof QualityRoute
  '/settings': typeof SettingsRoute
  '/summary': typeof SummaryRoute
  '/upload': typeof UploadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ask': typeof AskRoute
  '/chat': typeof ChatRoute
  '/data-sources': typeof DataSourcesRoute
  '/dataset-overview': typeof DatasetOverviewRoute
  '/dictionary': typeof DictionaryRoute
  '/executive': typeof ExecutiveRoute
  '/export': typeof ExportRoute
  '/governance': typeof GovernanceRoute
  '/lineage': typeof LineageRoute
  '/multilingual': typeof MultilingualRoute
  '/quality': typeof QualityRoute
  '/settings': typeof SettingsRoute
  '/summary': typeof SummaryRoute
  '/upload': typeof UploadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ask': typeof AskRoute
  '/chat': typeof ChatRoute
  '/data-sources': typeof DataSourcesRoute
  '/dataset-overview': typeof DatasetOverviewRoute
  '/dictionary': typeof DictionaryRoute
  '/executive': typeof ExecutiveRoute
  '/export': typeof ExportRoute
  '/governance': typeof GovernanceRoute
  '/lineage': typeof LineageRoute
  '/multilingual': typeof MultilingualRoute
  '/quality': typeof QualityRoute
  '/settings': typeof SettingsRoute
  '/summary': typeof SummaryRoute
  '/upload': typeof UploadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ask'
    | '/chat'
    | '/data-sources'
    | '/dataset-overview'
    | '/dictionary'
    | '/executive'
    | '/export'
    | '/governance'
    | '/lineage'
    | '/multilingual'
    | '/quality'
    | '/settings'
    | '/summary'
    | '/upload'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ask'
    | '/chat'
    | '/data-sources'
    | '/dataset-overview'
    | '/dictionary'
    | '/executive'
    | '/export'
    | '/governance'
    | '/lineage'
    | '/multilingual'
    | '/quality'
    | '/settings'
    | '/summary'
    | '/upload'
  id:
    | '__root__'
    | '/'
    | '/ask'
    | '/chat'
    | '/data-sources'
    | '/dataset-overview'
    | '/dictionary'
    | '/executive'
    | '/export'
    | '/governance'
    | '/lineage'
    | '/multilingual'
    | '/quality'
    | '/settings'
    | '/summary'
    | '/upload'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AskRoute: typeof AskRoute
  ChatRoute: typeof ChatRoute
  DataSourcesRoute: typeof DataSourcesRoute
  DatasetOverviewRoute: typeof DatasetOverviewRoute
  DictionaryRoute: typeof DictionaryRoute
  ExecutiveRoute: typeof ExecutiveRoute
  ExportRoute: typeof ExportRoute
  GovernanceRoute: typeof GovernanceRoute
  LineageRoute: typeof LineageRoute
  MultilingualRoute: typeof MultilingualRoute
  QualityRoute: typeof QualityRoute
  SettingsRoute: typeof SettingsRoute
  SummaryRoute: typeof SummaryRoute
  UploadRoute: typeof UploadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/summary': {
      id: '/summary'
      path: '/summary'
      fullPath: '/summary'
      preLoaderRoute: typeof SummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quality': {
      id: '/quality'
      path: '/quality'
      fullPath: '/quality'
      preLoaderRoute: typeof QualityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/multilingual': {
      id: '/multilingual'
      path: '/multilingual'
      fullPath: '/multilingual'
      preLoaderRoute: typeof MultilingualRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lineage': {
      id: '/lineage'
      path: '/lineage'
      fullPath: '/lineage'
      preLoaderRoute: typeof LineageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/governance': {
      id: '/governance'
      path: '/governance'
      fullPath: '/governance'
      preLoaderRoute: typeof GovernanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/export': {
      id: '/export'
      path: '/export'
      fullPath: '/export'
      preLoaderRoute: typeof ExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/executive': {
      id: '/executive'
      path: '/executive'
      fullPath: '/executive'
      preLoaderRoute: typeof ExecutiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dictionary': {
      id: '/dictionary'
      path: '/dictionary'
      fullPath: '/dictionary'
      preLoaderRoute: typeof DictionaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dataset-overview': {
      id: '/dataset-overview'
      path: '/dataset-overview'
      fullPath: '/dataset-overview'
      preLoaderRoute: typeof DatasetOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-sources': {
      id: '/data-sources'
      path: '/data-sources'
      fullPath: '/data-sources'
      preLoaderRoute: typeof DataSourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ask': {
      id: '/ask'
      path: '/ask'
      fullPath: '/ask'
      preLoaderRoute: typeof AskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AskRoute: AskRoute,
  ChatRoute: ChatRoute,
  DataSourcesRoute: DataSourcesRoute,
  DatasetOverviewRoute: DatasetOverviewRoute,
  DictionaryRoute: DictionaryRoute,
  ExecutiveRoute: ExecutiveRoute,
  ExportRoute: ExportRoute,
  GovernanceRoute: GovernanceRoute,
  LineageRoute: LineageRoute,
  MultilingualRoute: MultilingualRoute,
  QualityRoute: QualityRoute,
  SettingsRoute: SettingsRoute,
  SummaryRoute: SummaryRoute,
  UploadRoute: UploadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
