/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as TalktoSpeechRouteImport } from './routes/talkto-speech'
import { Route as SummaryRouteImport } from './routes/summary'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as MultilingualRouteImport } from './routes/multilingual'
import { Route as LineageRouteImport } from './routes/lineage'
import { Route as ExportRouteImport } from './routes/export'
import { Route as DictionaryRouteImport } from './routes/dictionary'
import { Route as AskRouteImport } from './routes/ask'
import { Route as IndexRouteImport } from './routes/index'

const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const TalktoSpeechRoute = TalktoSpeechRouteImport.update({
  id: '/talkto-speech',
  path: '/talkto-speech',
  getParentRoute: () => rootRouteImport,
} as any)
const SummaryRoute = SummaryRouteImport.update({
  id: '/summary',
  path: '/summary',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const MultilingualRoute = MultilingualRouteImport.update({
  id: '/multilingual',
  path: '/multilingual',
  getParentRoute: () => rootRouteImport,
} as any)
const LineageRoute = LineageRouteImport.update({
  id: '/lineage',
  path: '/lineage',
  getParentRoute: () => rootRouteImport,
} as any)
const ExportRoute = ExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => rootRouteImport,
} as any)
const DictionaryRoute = DictionaryRouteImport.update({
  id: '/dictionary',
  path: '/dictionary',
  getParentRoute: () => rootRouteImport,
} as any)
const AskRoute = AskRouteImport.update({
  id: '/ask',
  path: '/ask',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ask': typeof AskRoute
  '/dictionary': typeof DictionaryRoute
  '/export': typeof ExportRoute
  '/lineage': typeof LineageRoute
  '/multilingual': typeof MultilingualRoute
  '/settings': typeof SettingsRoute
  '/summary': typeof SummaryRoute
  '/talkto-speech': typeof TalktoSpeechRoute
  '/upload': typeof UploadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ask': typeof AskRoute
  '/dictionary': typeof DictionaryRoute
  '/export': typeof ExportRoute
  '/lineage': typeof LineageRoute
  '/multilingual': typeof MultilingualRoute
  '/settings': typeof SettingsRoute
  '/summary': typeof SummaryRoute
  '/talkto-speech': typeof TalktoSpeechRoute
  '/upload': typeof UploadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ask': typeof AskRoute
  '/dictionary': typeof DictionaryRoute
  '/export': typeof ExportRoute
  '/lineage': typeof LineageRoute
  '/multilingual': typeof MultilingualRoute
  '/settings': typeof SettingsRoute
  '/summary': typeof SummaryRoute
  '/talkto-speech': typeof TalktoSpeechRoute
  '/upload': typeof UploadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ask'
    | '/dictionary'
    | '/export'
    | '/lineage'
    | '/multilingual'
    | '/settings'
    | '/summary'
    | '/talkto-speech'
    | '/upload'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ask'
    | '/dictionary'
    | '/export'
    | '/lineage'
    | '/multilingual'
    | '/settings'
    | '/summary'
    | '/talkto-speech'
    | '/upload'
  id:
    | '__root__'
    | '/'
    | '/ask'
    | '/dictionary'
    | '/export'
    | '/lineage'
    | '/multilingual'
    | '/settings'
    | '/summary'
    | '/talkto-speech'
    | '/upload'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AskRoute: typeof AskRoute
  DictionaryRoute: typeof DictionaryRoute
  ExportRoute: typeof ExportRoute
  LineageRoute: typeof LineageRoute
  MultilingualRoute: typeof MultilingualRoute
  SettingsRoute: typeof SettingsRoute
  SummaryRoute: typeof SummaryRoute
  TalktoSpeechRoute: typeof TalktoSpeechRoute
  UploadRoute: typeof UploadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/talkto-speech': {
      id: '/talkto-speech'
      path: '/talkto-speech'
      fullPath: '/talkto-speech'
      preLoaderRoute: typeof TalktoSpeechRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/summary': {
      id: '/summary'
      path: '/summary'
      fullPath: '/summary'
      preLoaderRoute: typeof SummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/multilingual': {
      id: '/multilingual'
      path: '/multilingual'
      fullPath: '/multilingual'
      preLoaderRoute: typeof MultilingualRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lineage': {
      id: '/lineage'
      path: '/lineage'
      fullPath: '/lineage'
      preLoaderRoute: typeof LineageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/export': {
      id: '/export'
      path: '/export'
      fullPath: '/export'
      preLoaderRoute: typeof ExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dictionary': {
      id: '/dictionary'
      path: '/dictionary'
      fullPath: '/dictionary'
      preLoaderRoute: typeof DictionaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ask': {
      id: '/ask'
      path: '/ask'
      fullPath: '/ask'
      preLoaderRoute: typeof AskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AskRoute: AskRoute,
  DictionaryRoute: DictionaryRoute,
  ExportRoute: ExportRoute,
  LineageRoute: LineageRoute,
  MultilingualRoute: MultilingualRoute,
  SettingsRoute: SettingsRoute,
  SummaryRoute: SummaryRoute,
  TalktoSpeechRoute: TalktoSpeechRoute,
  UploadRoute: UploadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
